name: All checks pass

on:
  pull_request:
  merge_group:

jobs:
  enforce-all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@899c768d191b56eef585c18f8558da19e1f3e707 # v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
