name: Check spelling

on:
  pull_request:
  push:
    branches: [ master ]
  merge_group:

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
      with:
        check_filenames: true
        ignore_words_file: .codespellignore
        path: lib test extra
