name: Check spelling

on:
  pull_request:
  push:
    branches: [ master ]
  merge_group:

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
      with:
        check_filenames: true
        ignore_words_file: .codespellignore
        path: lib test extra
